permissions:
  contents: write

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
name: Readme Maintenance
jobs:
  update-readme:
    name: Update Readme
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Update Readme
        shell: powershell
        run: ./bin/update-readme.ps1
      - uses: stefanzweifel/git-auto-commit-action@v6
        name: Commit Readme Changes
        with:
          commit_message: "chore: Update Readme"
          commit_user_name: Readme Maintenance
          file_pattern: "*.md"
